### ISSUE TITLE
Update source links in MD files to use relative links

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#798] opened 2019-11-21 17:32 UTC
For our README's and CHANGELOG's we should update the links to follow the guidelines at https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md#link-guidelines. 

- [ ] Fix MD file links in the templates https://github.com/Azure/azure-sdk/search?l=Markdown&q=master&type=
- [ ] Fix MD file links in .NET https://github.com/Azure/azure-sdk-for-net/search?l=Markdown&q=master&type=
- [ ] Fix MD file links in Java https://github.com/Azure/azure-sdk-for-java/search?l=Markdown&q=master&type=
- [ ] Fix MD file links in JS https://github.com/Azure/azure-sdk-for-js/search?l=Markdown&q=master&type=
- [ ] Fix MD file links in Python https://github.com/Azure/azure-sdk-for-js/search?l=Markdown&q=master&type=
- [ ] Update release process to translate the absolute master links in the generated docs from the artifacts to be absolute release tag links and add check to not allow any relative links in the .MD files

**Comment by KarishmaGhiya** [comment] 2020-08-13 23:06
@weshaggard @sima-zhu 
I think we should update the last todo from
 ```Update release process to translate relative links in README and CHANGELOG files to be absolute based on the release tag```
TO  
```Update release process to translate the master links in the generated docs to be absolute release tag links and add check to not allow any relative links in the .MD files```

**Comment by sima-zhu** [comment] 2020-09-21 18:41
The issue is resolved by PRs:
https://github.com/Azure/azure-sdk-tools/pull/926
https://github.com/Azure/azure-sdk-tools/pull/895

Closed the issue for now. Please feel free to close it if anything left.

**Closed by sima-zhu** 2020-09-21 18:41 UTC
Labels: EngSys
