### ISSUE TITLE
Board Review: Azure Identity

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#1502] opened 2020-06-29 20:22 UTC
This is to review updates currently in preview in the Azure Identity libraries so that we can release them as GA.

## The Basics

* Service team responsible for the client library:
* Link to documentation describing the service:
* Contact email (if service team, provide PM and Dev Lead):

## About this client library

* Name of the client library:
* Languages for this review:
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: 
Identity:https://apiview.dev/Assemblies/Review/d6b64077934b4b7190038f4b8fd47098?diffRevisionId=35e75e85ff9c41c2962314130314093e

* Link to samples for champion scenarios:
[Application User Authentication](https://gist.github.com/schaabs/d1f2a4085851f5330acd5d3a96b0c99a)
### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: Identity: https://apiview.dev/Assemblies/Review/bb190f8005ab4271af6197e522615947?diffRevisionId=ac04da3825974e168f6fe37369748b17

* Link to samples for champion scenarios:
[Application User Authentication](https://github.com/g2vinay/KVSpec/blob/master/UserAuthAPI.md)
### Python

* Upload the api as a Draft PR.  Link to PR: https://apiview.dev/Assemblies/Review/0c9ff0d21d084b12b7664b6b2d911abc?diffRevisionId=435de02cd2074e14a4a25e1e60c26910
* Link to samples for champion scenarios:
[Application User Authentication](https://gist.github.com/chlowell/50859bb14dd79733bd81b143018e2186)

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/jonathandturner/azure-sdk-for-js/pull/2/files
* Link to samples for champion scenarios:
## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment] 2020-07-17 04:17
**.Net**

1. 
```
 public class ClientCertificateCredentialOptions : TokenCredentialOptions {      
        public bool EnablePersistentCache { get; set; }
}
```
- behavior of encrypted and persistent cache maybe not be transparent or obvious 
- maybe write a tester to check if encrypted cache exists first
- easier approach might be writing sample code to demonstrate scenario -- how to write code as user who doesn't know about the environment? 


2. 
```
        public ClientCertificateCredential(string tenantId, string clientId, string clientCertificatePath);
        public ClientCertificateCredential(string tenantId, string clientId, string clientCertificatePath, TokenCredentialOptions options);
	public ClientCertificateCredential(string tenantId, string clientId, string clientCertificatePath, ClientCertificateCredentialOptions options);
  	public ClientCertificateCredential(string tenantId, string clientId, X509Certificate2 clientCertificate);
        public ClientCertificateCredential(string tenantId, string clientId, X509Certificate2 clientCertificate, TokenCredentialOptions options);
        public ClientCertificateCredential(string tenantId, string clientId, X509Certificate2 clientCertificate, ClientCertificateCredentialOptions options);
```
- It's fine not to hide old constructor, but describe in documentation  

3. `public ClientCertificateCredential(string tenantId, string clientId, X509Certificate2 clientCertificate, TokenCredentialOptions options);`
    - shouldn't silently ignore properties that old constructor silently ignores; should throw
    - But maybe not be expected behavior if derived type is involved  
    - Follow up on this

```
 public class SharedTokenCacheCredential : TokenCredential {
        public SharedTokenCacheCredential();
        public SharedTokenCacheCredential(SharedTokenCacheCredentialOptions options);
        public SharedTokenCacheCredential(string username, TokenCredentialOptions options = null);
        public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken = default);
        public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken = default);
    }
```
- add `AuthenticationRecord` property

```
public class AuthenticationRecord {
        public void Serialize(Stream stream, CancellationToken cancellationToken = default);
        public Task SerializeAsync(Stream stream, CancellationToken cancellationToken = default);
}
```
- Have no control over serializers currently
- cross language serialization format guideline

`public static class KnownAuthorityHosts {}`
- how to name? 
- `AzureAuthorityHost` suggested 


**JS**

- Lagged behind a bit since GA because of MSAL (only alpha version now)
- When GA next month, will simutaenously shipping preview with MSAL integration
- MSAL will GA next Jan/Feb, but at some point (when MSAL have ICM support), could be good enough to be used in JS library 
- JS changes are minor--can assign architects to issue and get approval there


@schaabs **Action Items:** 
- Sample illustrating encrypted, persistent cache behavior for users not knowing about environment
- Describe old constructor for `ClientCertificateCredential()` in documentation 
- Follow up on what to do with old constructors that silently ignore options
- Add `AuthenticationRecord` to `SharedTokenCacheCredential` class
- Follow up on what to do with serializers as we now have no control over them 
    - decide on cross language serialization format guideline
- Decide how to name `KnownAuthorityHosts`
- JS changes are minor--can assign architects to issue and get approval there

**Comment by lilyjma** [comment] 2020-08-02 04:44
Hi @schaabs, is it okay to close this issue?

**Closed** 2023-03-01 18:33 UTC
Labels: architecture, board-review
