### ISSUE TITLE
Add multi-package support to JS release pipelines

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#232] opened 2019-03-07 20:15 UTC
All of the JS release pipelines can only publish one package at a time.  All of the other language release pipelines support multi-package releasing.

This is particularly important as the IoT team is going to be releasing through our partner pipeline soon and they have multiple packages they'll be releasing at once.

We also need to add a release pipeline for JS from blob to internal DevOps feed for testing.

**Comment by kurtzeborn** [comment] 2019-03-08 00:55
This is a duplicate of https://github.com/azure/azure-sdk-for-js/issues/1045

**Closed** 2019-03-08 00:55 UTC
Labels: EngSys
