### ISSUE TITLE
Automate Azure Identity multi tenant testing

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk#1346] opened 2020-05-19 05:56 UTC
We need to add multi-tenant testing to the list of automated tests we do in Azure Identity. The steps to do are listed below.

# Pre-requisites
- A user to access tenant A (with or without valid subscription) with permission to create a service principal, e.g. microsoft.com
- A user to access tenant B with a valid subscription and Global Administrator permission. Tenant B must have 2FA turned off.
- Azure CLI

# Initial setup
We need a few variables to run the test. We will store them in environment variables for convenience later.
- AZURE_TENANT_ID
The tenant id of tenant B
- TENANT_B_DOMAIN
The domain of tenant B, in the format of xxx.onmicrosoft.com
- AZURE_APP_NAME
The display name of the AAD multi-tenant application in tenant A
- AZURE_CLIENT_SECRET
The client secret for the AAD multi-tenant application in tenant A
- AZURE_USER
The user name of the AAD user in tenant B
- AZURE_USER_NAME
AZURE_USER@TENANT_B_DOMAIN
- AZURE_USER_PASSWORD
The password for this AAD user in tenant B

## Create a multi-tenant application in tenant A
Create a file `resource-access-permissions.json` with the following content:

```json
[
    {
        "resourceAppId": "cfa8b339-82a2-471a-a3c9-0fc0be7a4093",
        "resourceAccess": [
            {
                "id": "f53da476-18e3-4152-8e01-aec403e6edc0",
                "type": "Scope"
            }
        ]
    },
    {
        "resourceAppId": "00000003-0000-0000-c000-000000000000",
        "resourceAccess": [
            {
                "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
                "type": "Scope"
            }
        ]
    },
    {
        "resourceAppId": "00000002-0000-0000-c000-000000000000",
        "resourceAccess": [
            {
                "id": "a42657d6-7f20-40e3-b6f0-cee03008a62a",
                "type": "Scope"
            },
            {
                "id": "cba73afc-7f69-4d86-8450-4978e04ecd1a",
                "type": "Scope"
            },
            {
                "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
                "type": "Scope"
            },
            {
                "id": "5778995a-e1bf-45b8-affa-663a9f3f4d04",
                "type": "Role"
            }
        ]
    }
]
```

Login in CLI with an account and make sure the current subscription belongs to tenant A. Run command in CLI to create a multi-tenant application in tenant A
```bash
AZURE_CLIENT_ID=`az ad app create --display-name $AZURE_APP_NAME --password "Application@Pass123" --available-to-other-tenants true --native-app true --reply-urls http://localhost:8765 --required-resource-accesses resource-access-permissions.json -o json --query appId | tr -d '"'`
```

## Create a test user account in tenant B
Login in CLI with an Global Administrator account to tenant B:
```bash
az login --allow-no-subscription
```
Run command in CLI to create a user account in tenant B:
```bash
az ad user create --display-name $AZURE_USER --password "Charger@295_blue" --force-change-password-next-login false --user-principal-name $AZURE_USER_NAME
```

## Consent to the multi-tenant application from tenant B
Open the browser to `https://login.microsoftonline.com/{AZURE_TENANT_ID}/v2.0/adminconsent?client_id={AZURE_CLIENT_ID}&state=12345&redirect_uri=http://localhost:8765&scope=https://graph.microsoft.com/.default` and login with the Global Administrator account from tenant B and accept the requested permissions.

# Tests
We will verify the Azure Identity library is capable of authenticating
1) a user in tenant B with a multi-tenant application from tenant A
2) a multi-tenant application from tenant A directly to tenant B

First clone https://github.com/Azure/azure-sdk-for-java and build the project:
```bash
mvn -Dgpg.skip -Dinclude-non-shipping-modules -DskipTests install -Dspotbugs.skip -Dcheckstyle.skip -Djacoco.skip -Drevapi.skip
```

Then build an executable jar for the end-to-end tests:
```bash
mvn -Dgpg.skip -Dinclude-non-shipping-modules -DskipTests package -Dpackage-with-dependencies -Dspotbugs.skip -Dcheckstyle.skip -Djacoco.skip -Drevapi.skip -f sdk\e2e\pom.xml
```

## Test user authentication
Make sure the following environments are still set to the correct values:
- `AZURE_CLIENT_ID`: set from Azure CLI app creation command
- `AZURE_CLIENT_SECRET`: set from [Initial Setup](#initial-setup)
- `AZURE_USER_NAME`: set from [Initial Setup](#initial-setup)
- `AZURE_USER_PASSWORD`: set from [Initial Setup](#initial-setup)
- `AZURE_TENANT_ID`: set from [Initial Setup](#initial-setup)
- `AZURE_MULTI_TENANT_TEST_MODE`: set to `user`
- `AZURE_IDENTITY_TEST_PLATFORM`: set to `multitenant`

Run
```
java -jar sdk\e2e\target\azure-e2e-1.0.0-beta.1-jar-with-dependencies.jar
```

And it should print
```
SUCCESS: testUserPasswordCanAccessGraph - Successfully retrieved a user through a multi-tenant app.
```

## Test service principal authentication
Make sure the following environments are still set to the correct values:
- `AZURE_CLIENT_ID`: set from Azure CLI app creation command
- `AZURE_CLIENT_SECRET`: set from [Initial Setup](#initial-setup)
- `AZURE_USER_NAME`: set from [Initial Setup](#initial-setup)
- `AZURE_USER_PASSWORD`: set from [Initial Setup](#initial-setup)
- `AZURE_TENANT_ID`: set from [Initial Setup](#initial-setup)
- `AZURE_MULTI_TENANT_TEST_MODE`: set to `sp`
- `AZURE_IDENTITY_TEST_PLATFORM`: set to `multitenant`
 
Run
```
java -jar sdk\e2e\target\azure-e2e-1.0.0-beta.1-jar-with-dependencies.jar
```

And it should print
```
SUCCESS: testServicePrincipalCanAccessGraph - Successfully retrieved a user from another tenant.
```

# Clean up

## Delete the test user in tenant B
Run in Azure CLI:
```bash
az ad user delete --id $AZURE_USER_NAME
```

## Delete the multi tenant application in tenant A
First switch to any subscription in tenant A:
```bash
az account set --subscription {subscription ID}
```

Then delete the application
```bash
az ad app delete --id $AZURE_CLIENT_ID
```

**Comment by XuGuang-Yao** [comment] 2020-07-28 02:48
@jianghaolu - Hi, I see the test instrucation is marked as pending, but looks like you have already finished the test steps. So we are wondering should we start to do manual test? If so, can you tell us how to set the appropriate permissions, because our account currently cannot create users in the tenant.

![1](https://user-images.githubusercontent.com/53599438/88613280-b60f2c00-d0bf-11ea-85b4-10f5ce58e0c0.png)

**Comment by jianghaolu** [comment] 2020-07-29 21:17
The PR has been merged so the pending status can be removed.

You cannot create users in the microsoft.com tenant. You will need to create a new tenant.

**Comment by XuGuang-Yao** [comment] 2020-08-03 06:41
Hi, thank you for your update. We are focusing on this test. Could you please create two appropriate tenants for test?

**Comment by XuGuang-Yao** [comment] 2020-08-03 07:49
@jianghaolu - Hi, thank you for your update. After creating tenants, new subscriptions are also required. Could you please create two tenants and associated subscriptions for this test? And add our accounts into them as appropriate role?

**Comment by kurtzeborn** [comment] 2020-09-29 22:47
Labeling this "Client" but please work with the EngSys team as you do this.  We want to make sure it plugs into the rest of the system effectively.

**Comment by v-xuto** [comment] 2022-07-15 09:42
@jianghaolu - After creating tenants, new subscriptions are also required. Could you please create two tenants and associated subscriptions for this test? And add our accounts into them as appropriate role?

**Comment by v-jiaodi** [comment] 2022-11-23 09:21
@jianghaolu When testing according to the above test instruction and run the command 
```
AZURE_CLIENT_ID=`az ad app create --display-name $AZURE_APP_NAME --password "Application@Pass123" --available-to-other-tenants true --native-app true --reply-urls http://localhost:8765 --required-resource-accesses resource-access-permissions.json -o json --query appId | tr -d '"'``
```
We get the following error:
![image](https://user-images.githubusercontent.com/80496810/203505072-8b945214-9e04-4496-a30c-f199360aded0.png)

Please help to verify whether the test instruction is outdated. If yes, please help to update the test instruction, and we will retest. If not, please help to check the error.

**Comment by joshfree** [comment] 2022-11-26 01:00
@billwert could you follow upw ith @v-jiaodi here?

**Comment by v-jiaodi** [comment] 2023-05-09 07:13
> @joshfree , @jianghaolu When testing according to the above test instruction and run the command
> 
> ```
> AZURE_CLIENT_ID=`az ad app create --display-name $AZURE_APP_NAME --password "Application@Pass123" --available-to-other-tenants true --native-app true --reply-urls http://localhost:8765 --required-resource-accesses resource-access-permissions.json -o json --query appId | tr -d '"'``
> ```
> 
> We get the following error: ![image](https://user-images.githubusercontent.com/80496810/203505072-8b945214-9e04-4496-a30c-f199360aded0.png)
> 
> Please help to verify whether the test instruction is outdated. If yes, please help to update the test instruction, and we will retest. If not, please help to check the error.

@billwert In Azure Identity SDK RC Test Pass for May 2023, we are still facing this issue. Can you help us check or provide some assistance?

**Comment by billwert** [comment] 2023-05-24 22:59
Hi @v-jiaodi I will take a look at this soon (probably next week.)

**Comment by joshfree** [comment] 2023-08-24 18:38
Copied this java specific failure here: https://github.com/Azure/azure-sdk-for-java/issues/36500 so that it'll be easier to track.

**Comment by billwert** [comment] 2023-12-21 22:45
Closed the other issue as this isn't java specific. Will work with EngSys in the new year to clean this up; need some guidance on interacting with the second tenant.

**Comment by joshfree** [comment] 2024-01-08 20:36
@billwert can you distill this down into actionable instructions for the other languages and update the issues here:



https://github.com/orgs/Azure/projects/134/views/6?filterQuery=-status%3ADone+Automate+Azure+Identity+SDK
![Image](https://github.com/Azure/azure-sdk/assets/1302850/b381e057-797b-4113-9587-fc843a06d71d)

**Comment by g2vinay** [comment] 2024-04-01 18:09
Duplicate of #35786
Closing it.

**Closed by g2vinay** 2024-04-01 18:09 UTC
Labels: EngSys, Client, Azure.Identity, test-manual-pass
