### ISSUE TITLE
Board Review: Management Plane Namespace Review Microsoft.EdgeMarketPlace

### ISSUE THREAD

**Issue by aneesh-ponneth** [Azure/azure-sdk#6585] opened 2023-08-31 21:06 UTC
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: azstc@microsoft.com
* Main contacts: anponnet@microsoft.com; lloydg@microsoft.com
* Expected code complete date: 09/06/2023
* Expected release date: 09/15/2023

## About the Service (required)

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs/pull/25556
* Link to GitHub issue for previous review sessions, if applicable:  

## Namespace Proposals (required per language)

**In the examples below please replace every occurrence of [ResourceProviderName] with your the service resource provider name. Be sure to keep the casing shown with [ResourceProviderName] when replacing it with the service resource provider name.**

- **.NET:** `Azure.ResourceManager.Microsoft.EdgeMarektPlace`
- **Java:** `azure-resourcemanager-microsoft.edgemarketplace (com.azure.resourcemanager.microsoft.edgemarketplace)`
- **Go/Golang:** `sdk/resourcemanager/microsoft.edgemarketplace/armmicrosoft.edgemarketplace`
- **JavaScript:** `@azure/arm-microsoft.edgemarketplace`
- **Python:** `azure-mgmt-microsoft.edgemarketplace`

## Thank you!

**Comment by ArthurMa1978** [comment] 2023-09-04 10:16
This is dup with https://github.com/Azure/azure-sdk/issues/6586

**Comment by ronniegeraghty** [comment] 2023-09-05 17:12
Closing, as this issue is a duplicate of an existing issue #6586

**Closed by ronniegeraghty** 2023-09-05 17:12 UTC
Labels: architecture, board-review, mgmt-namespace-review
