### ISSUE TITLE
CIs are blocked on APIView approvals

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#4818] opened 2022-09-09 18:41 UTC
At least for .NET - though I suspect something like this is true for all languages - the tests.yml runs in two modes: normal CI e.g., when merges to main occur; and releases. Releases definitely should be gated on APIView approval, but CIs are failing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1841596&view=results

Not only does this send notifications of build failures, but also shows a red "X" on the commits in GitHub which may not inspire confidence for people looking at general commit status. As you can see from the build above, it otherwise would've worked.

If the tests.yml-driven pipeline isn't be used for release i.e., not manually invoked, can we skip the APIView approval check?

/cc @weshaggard @benbp

**Comment by maririos** [comment] 2022-09-09 18:45
> If the tests.yml-driven pipeline isn't be used for release i.e., not manually invoked, can we skip the APIView approval check?

Will this help? https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/403/Build-and-Release-checks?anchor=how-to-override-release-check

**Comment by maririos** [comment] 2022-09-09 18:46
Also, what you are saying sound slike it is by design. We want to make sure that teams know that their pipeline is broken until they get the approval, instead of them waiting to do a release and then finding out that they need to ask for it.

@praveenkuttappan for more context

**Comment by heaths** [comment] 2022-09-09 18:46
CIs are run automatically, so no. But good to know for manual runs. It would be nice if the variable was predefined so it was more discoverable, though. If each pipeline defines it with the desired default - probably `false` - people see it in the per-run variables list and can change it as necessary.

**Comment by heaths** [comment] 2022-09-09 18:47
> Also, what you are saying sound slike it is by design. We want to make sure that teams know that their pipeline is broken until they get the approval, instead of them waiting to do a release and then finding out that they need to ask for it.
> 
> @praveenkuttappan for more context

It's misleading. It's not broken. APIView sign-off is only needed to release. Normal CIs are just to make sure everything builds right. This sends the wrong signal.

**Comment by maririos** [comment] 2022-09-09 18:50
From the same wiki I sent you:
> Build job will be marked as failed if latest revision of automatically created API review is not yet approved and if package version is GA if a release date is present in Change log for the version. Approval status is ignored and build won't fail if release date is unreleased in change log. So we need to ensure API review is approved in API review tool whenever developer makes a change to API review tool.

**Comment by heaths** [comment] 2022-09-09 18:57
Understood, but I think it's misleading. APIView approval status doesn't matter until you ship; otherwise, you're just signaling that a CI build failed even though that build isn't capable of releasing (only manual runs are).

Let me put it this way: if users come to our repos and see this, you think that inspires confidence in our build just because we validate an API is approved when we don't even plan to - and can't, given it's a triggered CI - release it?

<img width="362" alt="image" src="https://user-images.githubusercontent.com/1532486/189424068-d9a00a92-a608-4a38-8429-1bc1085fcac6.png">

When I see that on repos, it generally raises a red flag to me about quality.

**Comment by weshaggard** [comment] 2022-09-09 20:59
@heaths we don't start failing CI or scheduled pipelines until there is a signal that you plan to release. That signal comes from the changelog once you stamp in a ship date and you have a GA version we start validating this in the build. That was a major feature request folks wanted because they wanted a signal before they hit the approval on the release stage so it would fail earlier. Most folks don't ever check-in a release date until right before they plan to do a release and at that time the failure is an indication that they need to do something before they can release which in this case is to get the APIs approved. 

Also as for the variable promotion, in this case it should be an exceptional case so not something someone does normally so we don't want to advertise that option.

**Comment by weshaggard** [comment] 2022-09-09 21:02
I'm going to close this as I believe this is working as designed and at this point I'm not inclined to change that design. We can perhaps improve the errors or documentation but I think the behavior is what we want.

**Closed by weshaggard** 2022-09-09 21:02 UTC
Labels: Central-EngSys
