### ISSUE TITLE
[Releases] Automate sanity/smoke testing

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#476] opened 2019-07-09 17:40 UTC
Each package release required manual testing and signoff from teams before shipping. 

* What steps were taken to verify that artifacts were ready for release? 
* Can these steps be automated and optimized to run in a few minutes?
* Can automation runs be kicked off after successful artifact production for release builds? 

For those things that can't be automated we should collect best practices so we're applying success criteria consistently across sanity checks.

**Comment by kurtzeborn** [comment] 2019-08-20 19:35
This is possibly related to or a dupe of azure/azure-sdk-for-js#2783

**Comment by mitchdenny** [comment] 2020-06-01 01:02
@kurtzeborn is this related to Unified Pipelines? I'm trying to close that epic down ;)

**Comment by mitchdenny** [comment] 2020-07-10 02:12
I'm gonna take a risk and close this one ;)

**Closed by mitchdenny** 2020-07-10 02:12 UTC
