### ISSUE TITLE
Detect & inject build targeting strings for CI builds

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk#304] opened 2019-04-11 17:45 UTC
When a CI build starts, it should detect which libraries have actually been changed, and then supply build targeting string(s) so that only the changed libraries and any libraries that depend on them are built and tested.

**Comment by weshaggard** [comment] 2019-04-12 18:20
related to https://github.com/Azure/azure-sdk/issues/192

**Comment by mitchdenny** [comment] 2019-05-08 20:04
Closed as dupe of #192.

**Closed** 2019-05-08 20:03 UTC
Labels: EngSys, Epic
